ipAddr: 39.105.35.4

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  elasticsearch:
    rest:
      uris: ["http://39.105.35.4:9200"]
  session:
    store-type: redis
  redis:
    host: ${ipAddr}

server:
  port: 12000