spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GFWFUWzqBB2D6VdEdvy
      secret-key: 1MHi2fgrdSC17xDg9ViPrDH3Zx0QZ8
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: ty-gulimall.oss-cn-beijing.aliyuncs.com

  application:
    name: gulimall-third-party

server:
  port: 30000